import RPi.GPIO as GPIO
import time

servoPin=18
GPIO.setmode(GPIO.BOARD)
GPIO.setup(servoPin,GPIO.OUT)
p = GPIO.PWM(servoPin, 50)
p.ChangeDutyCycle(5)
time.sleep(0.5)
p.ChangeDutyCycle(7.5)
time.sleep(0.5)
p.ChangeDutyCycle(10)
time.sleep(0.5)
p.ChangeDutyCycle(12.5)
time.sleep(0.5)
p.ChangeDutyCycle(10)
time.sleep(0.5)
p.ChangeDutyCycle(7.5)
time.sleep(0.5)
p.ChangeDutyCycle(5)
time.sleep(0.5)
p.ChangeDutyCycle(2.5)
time.sleep(0.5)
p.stop() 
GPIO.cleanup()